name: TestAndMerge
on: 
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  status: {}
jobs:
 run_tests:
  runs-on: ubuntu-latest
  steps:
    - name: Checkout the repository
      uses: actions/checkout@v2
    - name: Set up JDK 19
      uses: actions/setup-java@v1
      with:
       java-version: 19
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
       path: ~/.m2
       key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
       restore-keys: ${{ runner.os }}-m2
    - name: Run tests with Maven
      run: mvn -B test --file pom.xml
    - name: automerge  
      uses: reitermarkus/automerge@v2
      with:
          token: ${{ secrets.MY_GITHUB_TOKEN }}
          merge-method: rebase
          do-not-merge-labels: never-merge
          required-labels: automerge
          pull-request: ${{ github.event.inputs.pull-request }}
          review: ${{ github.event.inputs.review }}
          dry-run: true
